### ISSUE TITLE
Running Test application in Linux

### ISSUE THREAD

**Issue by mdavis777** [porsager/busylight#10]
I am having issues running the test application through linux command line.  It always hangs while connecting.  

Fedora 26 64Bit
Tried both Node js 8.4.0 and Node js 6.11.2 
Windows seems to work fine

**Comment by mdavis777** [comment]
Do you happen to have the API to communicate the light?
I would be interested in using it to create a C/C++ library.

**Comment by porsager** [comment]
You can check out their USB Api documentation attached here. I'm not sure it's the newest version, but you can get it by writing plenom if not.
[Busylight.API.rev.2.2.-.22052015.pdf](https://github.com/porsager/busylight/files/1270655/Busylight.API.rev.2.2.-.22052015.pdf)

**Comment by porsager** [comment]
With regards to your original issue, did node-hid compile correctly? You can check here for requirements [node-hid](https://github.com/node-hid/node-hid)

It's some time since i updated the required version, so there might be an easy fix by updating node-hid to the newest version...

**Comment by mdavis777** [comment]
Yep it compiled correctly.  It might be some sort of version incompatibility.  Thanks for the API a C/C++ library will better meet my needs so I will be pursing that over the node one.
