### ISSUE TITLE
How to keep the light alive?

### ISSUE THREAD

**Issue by robimac04** [porsager/busylight#11]
Hello,

I've set the default options, with keepalive as true. However, this is not working. The light constantly turns off after 30 secs. 

Is there a function of keepalive, so that I can use it in a one-liner?

Thank you very much.

**Comment by porsager** [comment]
Hi. I actually just released version 0.3.2 yesterday which has a fix for this in the new protocol. Are you using that version?

**Comment by robimac04** [comment]
Yes, I'm using the latest version. 

Thank you for your very quick response.

**Comment by porsager** [comment]
Ok good.

Does it turn back on after the 30 seconds?
Do you know which busylight model you have? (does the mount have magnets or only tape?)

**Comment by robimac04** [comment]
No, once it turns off, it stays off. 
The model I'm using is the one only with tape (UC Omega).

Here is the code I'm using:
```
var busylight = require('/usr/local/testdrive/busylight/lib');
var bl = busylight.get();

bl.defaults({
  keepalive: true,
  color: 'green'                                                                                                                                                                                                                                                                                                                                                                                                                            
});

bl.light(); 
```
Is there something missing?

**Comment by porsager** [comment]
Ah I see.. I haven't tested the Omega yet. I saw that there was a different option for it's timeout in the spec, so I'll just take a quick look and see if I can fix it easily.

**Comment by robimac04** [comment]
I just figured out that the keepalive does work for the ringtone. The light turns off but it keeps ringing...

**Comment by porsager** [comment]
Hmm, maybe there's an issue with the default light.. could you try to use `bl.light('green')` in your example above instead?

**Comment by robimac04** [comment]
Yes, but the issue still persists...

**Comment by porsager** [comment]
I'm not able to replicate this issue with my setup, could you give some more details about your system?

**Comment by robimac04** [comment]
My system is:

* MacBook Pro 2015 (busylight direct attached)
* macOS 10.13.2 High Sierra
* node.js version 8.9.1

**Comment by porsager** [comment]
Hi @robimac04 .. Could you try again with a fresh install and make sure to keep your process running?
