### ISSUE TITLE
Adjust busylight brightness

### ISSUE THREAD

**Issue by robimac04** [porsager/busylight#14]
Hello,

is it possible to adjust the brightness via API? The light is very low when using green color, compared to the original software on Windows (see picture).

![image 2017-12-11 08 14 56](https://user-images.githubusercontent.com/19255328/33819651-cd9c477c-de4b-11e7-9166-bd6f8ffa85e6.jpg)

**Comment by porsager** [comment]
Hi. That's definately a regression. I'll look into it now.

**Comment by porsager** [comment]
Hmm.. Could you try to provide the code you use? I've only been able to get my hands on a regular busylight which worked fine, and per the spec there shouldn't be a difference between that and the kuando box.

**Comment by robimac04** [comment]
It's the cloned repository in combination with a JS file to activate it. Content:
```
var busylight = require('/usr/local/testdrive/busylight/lib');
var bl = busylight.get();

bl.light('green');
```

The files in `/usr/local/testdrive/busylight/lib` are the same as in the repository.

**Comment by porsager** [comment]
Could you try to set `degamma: false` ?

**Comment by robimac04** [comment]
Okay thanks, I will try that.

**Comment by robimac04** [comment]
I've tried it, but it's still as dark as shown on the picture.

**Comment by porsager** [comment]
Hi @robimac04 ... sorry I never got back to you, but I just realized that the css color `green` isn't full green like `rgb(0, 255, 0)`, but rather only half of green `rgb(0, 255, 0)`.

I'm pretty sure if you do `rgb(0, 255, 0)` or `#00FF00` you'll get the same brightness..

Sorry i didn't realize this from the start :P

**Comment by robimac04** [comment]
No worries :-)

It works now, thank you very much for your support 👍

**Comment by aftabjan** [comment]
Hi @porsager, I have been facing the same issue of color brightness as you replied to @robimac04  and the solution worked for him to use RGB, but the same when I apply it doesn't work and I don't get a full bright color.
