### ISSUE TITLE
Undefined commands

### ISSUE THREAD

**Issue by foxbutterfly** [porsager/busylight#16]
Hi there,
after solving a lot of issues I got stuck on this specific one;
I upgraded my NODE_MODULE_VERSION from 48 to 57 with the command
`rm -rf node_modules && npm install`
And now I always get in the input field from node the hint "undefined"
`> var busylight = require('busylight').get()`
`undefined`

The busylight file is under ~/node_modules

I'm using version npm 5.8.0 & node 8.11.1

I'm working with an Xubuntu system on version 16.04.4 LTS

Does anyone got the same issue or a way how to fix it?

**Comment by foxbutterfly** [comment]
For anyone having this issue, I realized that the input field cannot give anything back from connecting with the light, so its says undefined. If you just use the other commands it works totally fine

**Comment by porsager** [comment]
Hi @foxbutterfly .. Glad you came back to update your issue, and sorry I didn't get to respond.

And yes, assigning to a variable in js will always return undefined, but the `busylight` variable above should hold the instance for the connected busylight.
