### ISSUE TITLE
Install not working on a plain new installation of ubuntu 15.10

### ISSUE THREAD

**Issue by garbast** [porsager/busylight#2]
On trying the below:

sudo npm install --global busylight

i get the following error message:

sebastian@sftp520-linux:~$ sudo npm install --global busylight
[sudo] Passwort für sebastian: 
\

> node-hid@0.3.1 preinstall /usr/lib/node_modules/iambusy/node_modules/busylight/node_modules/node-hid
> sh get-hidapi.sh

Klone nach 'hidapi' ...
remote: Counting objects: 1965, done.
remote: Total 1965 (delta 0), reused 0 (delta 0), pack-reused 1965
Empfange Objekte: 100% (1965/1965), 2.80 MiB | 430.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (1086/1086), Fertig.
Prüfe Konnektivität ... Fertig.
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "busylight"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/hidapi
npm ERR! 404 
npm ERR! 404 'hidapi' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'node-hid'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sebastian/npm-debug.log

I even tried to install node-hid globaly before installing busylight, but that did not fixed it.

**Comment by porsager** [comment]
Hi.

The error seems to be related to node-hid. Did you follow the compile and install description for node-hid on linux? You can find them here: https://github.com/node-hid/node-hid#compiling-from-source

**Comment by porsager** [comment]
Ah sorry. It seems node-hid made some important updates, so i updated the version to 0.5.1 which i think might solve your issue.

It's been published to npm now, so try to do an npm install again.

Let me know if it works for you since i don't have Ubuntu to test on myself right here..
Thanks.

**Comment by garbast** [comment]
Thanks for your awesome fast reaction for a holiday :). I tried to install it and it's working now.

Thank you and have a nice weekend.

**Comment by porsager** [comment]
That's great! And thanks for letting me know ;)
