### ISSUE TITLE
Busylight in web application

### ISSUE THREAD

**Issue by cdiscla** [porsager/busylight#20]
Hello, this is not an issue but a question ... your lib works great as node app but i would need to use it in my web application project. 
I have tried to use browserify but cannot make it work. Before banging my head, i would like if you or anyone have tried something similar. 
I would need to include some js scripts in my <script> tag to use it on the client side. Is it possible?
Thanks in advance and greetings

**Comment by porsager** [comment]
Hi @cdiscla 

This module is only for nodejs, not the browser. It relies on [`node-hid`](https://github.com/node-hid/node-hid) which is a native (c++) nodejs module that cannot run in the browser.

I suppose it might be possible to make it work in the browser with the [WebUSB API](https://developer.mozilla.org/en-US/docs/Web/API/USB) but that's not something I have time to look into unfortunately.

If you by any chance want this to work in either nwjs or electron, there's instructions for that at the bottom of the readme, and in the node-hid repo.
