### ISSUE TITLE
Upgrade dependency for node-hid to version 2.x?

### ISSUE THREAD

**Issue by lauer** [porsager/busylight#28]
Since I want to use this package in a newer version of ElectronJS cross-platform, I would like to have busylight to use node-hid 2.x, so it can use a precompiled version of node-hid.

**Comment by porsager** [comment]
Sounds like a good idea.. PR's are welcome, I won't have time in the near future to look at it myself.

**Comment by GregorBiswanger** [comment]
Please accept the PR. I also tested it locally again. It works.

**Comment by GregorBiswanger** [comment]
Please please accept the PR.
