### ISSUE TITLE
Usage..

### ISSUE THREAD

**Issue by Kerwood** [porsager/busylight#5]
Hi there.. Is it possible to make am Express server that listens for a POST message and turns the busylight on accordingly?

I'm trying to installed the busylight package but gets this error..

http://pastebin.com/vzVLT7fQ

I've been searching around but cant really figure it out. 
I'm on Ubuntu 15.04

**Comment by Kerwood** [comment]
I got it.. 
First ran `npm install node-pre-gyp -g`
Then afterwards `npm install node-hid`

**Comment by porsager** [comment]
Great to see you figured it out ;) 

Did node-pre-gyp not pop up as a requirement in the npm logs when you did the initial install?

**Comment by Kerwood** [comment]
Not sure.. Cant really remember to be honest..

**Comment by porsager** [comment]
Ok :) just wondered if it's something that might make sense to add to the readme.. I'll just check it out myself on a clean system.

Thanks.
