### ISSUE TITLE
Set busylight from bash/CLI?

### ISSUE THREAD

**Issue by runestone74** [porsager/busylight#9]
I would like to use my unused Busylight to show status on different Home Assistant alerts ( https://home-assistant.io/ ) but since my coding skills are slim to none, I have a hard time making ie a bash script for simple actions like"red light on when the water is too hot" etc. Would someone guide me in the right direction, preferably with some sample script, please :) (just for the Busylight action, inside a bash script)

**Comment by porsager** [comment]
It's a very good idea to make support for a CLI in this module, but I don't have the time to look closer at it right now. I'll leave this issue open, and then I hope i can get around to it soon.

With regards to the bash script it should be easier once there's CLI support for it, but until then you could run node with code directly like `node -r 'require('busylight').get().ring().pulse()'` if you don't want to save a file for it.

**Comment by mdavis777** [comment]
I am also having a lot of problems getting the light to respond at all.  It seems to be hanging on trying to connect.

**Comment by porsager** [comment]
@mdavis777 could you create a new issue with as much detail about your setup and the problem as possible?

**Comment by porsager** [comment]
Someone apparently went ahead and wrapped busylight as a cli module ;) Awesome

https://github.com/jamesrichford/busylight-cli
